### ISSUE TITLE
Typo under Notifications Settings menu

### ISSUE THREAD

**Issue by Amolith** [merrychap/decentralized_chat#1]
There's a typo under the Notifications settings menu. The sixth option down is for `Invitiations for me` and it should be `Invitations for me` without the "I" after the first "T".

I have to say, I *love* the new update! :slightly_smiling_face:

**Comment by konatabrk** [comment]
Can you tell me the name of the file that contains this typo?

**Comment by Amolith** [comment]
@merrychap Let me look around for it.

**Comment by konatabrk** [comment]
Are you sure that this issue dedicated to my project?
I have run `grep -r "Invitiations for me" .` command and it didn't find anything

**Comment by Amolith** [comment]
I am so sorry. The project that I should have filed the bug report for was [here](https://github.com/ChristianPauly/fluffychat). Same project name just a different user. My apologies.

**Comment by konatabrk** [comment]
Ah, it's all okay, don't worry :D
You are always welcome to report a bug for this project as well! :)
